import Head from 'next/head';
import { Share } from '@capacitor/share';
import {IonHeader, IonTitle, IonToolbar, IonPage, IonContent, IonFooter} from '@ionic/react';
import { Capacitor } from '@capacitor/core';
import Link from "next/link";
import React, { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function About() {
    const share = async () => {
        await Share.share({
            title: 'Simons YT Channel',
            text: 'Learn to build awesome mobile apps!',
            url: 'https://www.youtube.com/simongrimmdev_',
            dialogTitle: 'Share with freiends'
        });
    };

    // useEffect(() => {
    //     // setupIonicReact();
    // }, []);

    const router = useRouter();

    // useEffect(() => {
    //     // Detect the platform and add platform-specific CSS classes
    //     if (typeof window !== 'undefined' && window.Ionic) {
    //         document.body.classList.add('md');
    //     }
    // }, [router]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/*{Capacitor.isNativePlatform() && (*/}
            {/*    <IonHeader>*/}
            {/*        <IonToolbar color="primary">*/}
            {/*            <IonTitle>Simons Capacitor App</IonTitle>*/}
            {/*        </IonToolbar>*/}
            {/*    </IonHeader>*/}
            {/*)}*/}

            <IonHeader style={{boxShadow: `0 2px 4px -1px rgba(0,0,0,.2), 0 4px 5px 0 rgba(0,0,0,.14), 0 1px 10px 0 rgba(0,0,0,.12)`}}>
                <IonToolbar>
                    <IonTitle>Simons Capacitor App</IonTitle>
                </IonToolbar>
            </IonHeader>

            <IonContent className="ion-padding" fullscreen>
                <h1 style={{color: `red`}}>About</h1>

                <ion-card>
                    <ion-card-header>
                        <ion-card-title>sdfsdf</ion-card-title>
                    </ion-card-header>
                    <ion-card-content>sdf sdoufiodsf idosuf</ion-card-content>
                </ion-card>

                <ion-card>
                    <ion-card-header>
                        <ion-card-title>a asdfsdf</ion-card-title>
                    </ion-card-header>
                    <ion-card-content>sdf sdoufiodsf idosuf</ion-card-content>
                </ion-card>

                <Link href="/list">List</Link>
                <Link href="/">Home</Link>
            </IonContent>

            <IonFooter>
                <IonToolbar>
                    <IonTitle>Footer</IonTitle>
                </IonToolbar>
            </IonFooter>

        </>
    );
}
